version: "3.7"

name: exercise-api

services:
  api:
    build: .
    container_name: exercise-tracker-api
    command: tail -f /dev/null
    volumes:
      - ..:/home/node/app
    ports:
      - 9001:443
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.4
    container_name: mongodb
    restart: always
    volumes:
      - ./data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: mongo-admin
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017
    depends_on:
      - mongo
